
// src/lib/ccgVessels.ts

export interface CCGVessel {
  value: string; // Typically the vessel name, used as the unique ID for selection
  label: string; // The display name for the vessel
}

export const ccgVesselList: CCGVessel[] = [
  { value: "CCGS Amundsen", label: "CCGS Amundsen" },
  { value: "CCGS Ann Harvey", label: "CCGS Ann Harvey" },
  { value: "CCGS Arluk", label: "CCGS Arluk" },
  { value: "CCGS Arrow Post", label: "CCGS Arrow Post" },
  { value: "CCGS Baie Comeau", label: "CCGS Baie Comeau" },
  { value: "CCGS Bamfield", label: "CCGS Bamfield" },
  { value: "CCGS Bartlett", label: "CCGS Bartlett" },
  { value: "CCGS Bickerton", label: "CCGS Bickerton" },
  { value: "CCGS Brad Adlor", label: "CCGS Brad Adlor" },
  { value: "CCGS Brandy", label: "CCGS Brandy" },
  { value: "CCGS Cap Breton", label: "CCGS Cap Breton" },
  { value: "CCGS Cape Caution", label: "CCGS Cape Caution" },
  { value: "CCGS Cape Discovery", label: "CCGS Cape Discovery" },
  { value: "CCGS Cape Edensaw", label: "CCGS Cape Edensaw" },
  { value: "CCGS Cape Egmont", label: "CCGS Cape Egmont" },
  { value: "CCGS Cape Farewell", label: "CCGS Cape Farewell" },
  { value: "CCGS Cape Fox", label: "CCGS Cape Fox" },
  { value: "CCGS Cape Franklin", label: "CCGS Cape Franklin" },
  { value: "CCGS Cape Hearne", label: "CCGS Cape Hearne" },
  { value: "CCGS Cape Kuper", label: "CCGS Cape Kuper" },
  { value: "CCGS Cape Light", label: "CCGS Cape Light" },
  { value: "CCGS Cape Mercy", label: "CCGS Cape Mercy" },
  { value: "CCGS Cape Naden", label: "CCGS Cape Naden" },
  { value: "CCGS Cape Norman", label: "CCGS Cape Norman" },
  { value: "CCGS Cape Palmerston", label: "CCGS Cape Palmerston" },
  { value: "CCGS Cape Providence", label: "CCGS Cape Providence" },
  { value: "CCGS Cape Roger", label: "CCGS Cape Roger" },
  { value: "CCGS Cape Sable", label: "CCGS Cape Sable" },
  { value: "CCGS Cape Sand", label: "CCGS Cape Sand" },
  { value: "CCGS Cape Scott", label: "CCGS Cape Scott" },
  { value: "CCGS Cape St. James", label: "CCGS Cape St. James" },
  { value: "CCGS Cape St. Lawrence", label: "CCGS Cape St. Lawrence" },
  { value: "CCGS Cape Storm", label: "CCGS Cape Storm" },
  { value: "CCGS Captain Goddard M.S.M.", label: "CCGS Captain Goddard M.S.M." },
  { value: "CCGS Captain Molly Kool", label: "CCGS Captain Molly Kool" },
  { value: "CCGS Caribou Isle", label: "CCGS Caribou Isle" },
  { value: "CCGS Clarks Harbour", label: "CCGS Clarks Harbour" },
  { value: "CCGS Constable Carrière", label: "CCGS Constable Carrière" },
  { value: "CCGS Cove Isle", label: "CCGS Cove Isle" },
  { value: "CCGS Cygnus", label: "CCGS Cygnus" },
  { value: "CCGS Des Groseilliers", label: "CCGS Des Groseilliers" },
  { value: "CCGS Earl Grey", label: "CCGS Earl Grey" },
  { value: "CCGS Eckaloo", label: "CCGS Eckaloo" },
  { value: "CCGS Edward Cornwallis", label: "CCGS Edward Cornwallis" }, // Note: May be renamed, e.g., Suêtes
  { value: "CCGS G. Peddle S.C.", label: "CCGS G. Peddle S.C." },
  { value: "CCGS George R. Pearkes", label: "CCGS George R. Pearkes" },
  { value: "CCGS Gordon Reid", label: "CCGS Gordon Reid" },
  { value: "CCGS Griffon", label: "CCGS Griffon" },
  { value: "CCGS Henry Larsen", label: "CCGS Henry Larsen" },
  { value: "CCGS Hudson", label: "CCGS Hudson" }, // Note: Decommissioned, but historically significant
  { value: "CCGS Isle Rouge", label: "CCGS Isle Rouge" },
  { value: "CCGS Jean Goodwill", label: "CCGS Jean Goodwill" },
  { value: "CCGS John Cabot", label: "CCGS John Cabot" },
  { value: "CCGS John G. Diefenbaker", label: "CCGS John G. Diefenbaker" }, // Note: Future Polar Icebreaker
  { value: "CCGS Judy LaMarsh", label: "CCGS Judy LaMarsh" },
  { value: "CCGS Kelso", label: "CCGS Kelso" },
  { value: "CCGS Labrador", label: "CCGS Labrador" }, // Note: Historical, but for example
  { value: "CCGS Leeway", label: "CCGS Leeway" },
  { value: "CCGS Limnos", label: "CCGS Limnos" },
  { value: "CCGS Louis S. St-Laurent", label: "CCGS Louis S. St-Laurent" },
  { value: "CCGS M. Charles M.B.", label: "CCGS M. Charles M.B." },
  { value: "CCGS MacLaren", label: "CCGS MacLaren" },
  { value: "CCGS Malpeque Bay", label: "CCGS Malpeque Bay" },
  { value: "CCGS Martha L. Black", label: "CCGS Martha L. Black" },
  { value: "CCGS Mary Hichens", label: "CCGS Mary Hichens" },
  { value: "CCGS McIntyre Bay", label: "CCGS McIntyre Bay" },
  { value: "CCGS McLean", label: "CCGS McLean" },
  { value: "CCGS Moytel", label: "CCGS Moytel" },
  { value: "CCGS Otter Bay", label: "CCGS Otter Bay" },
  { value: "CCGS Pennant Bay", label: "CCGS Pennant Bay" },
  { value: "CCGS Pierre Radisson", label: "CCGS Pierre Radisson" },
  { value: "CCGS Provo Wallis", label: "CCGS Provo Wallis" },
  { value: "CCGS Race Point", label: "CCGS Race Point" },
  { value: "CCGS Ralph T. Beasley", label: "CCGS Ralph T. Beasley" },
  { value: "CCGS Sambro", label: "CCGS Sambro" },
  { value: "CCGS Samuel Risley", label: "CCGS Samuel Risley" },
  { value: "CCGS Sault Ste. Marie", label: "CCGS Sault Ste. Marie" },
  { value: "CCGS Seal", label: "CCGS Seal" },
  { value: "CCGS Sipu Muin", label: "CCGS Sipu Muin" },
  { value: "CCGS Sir John Franklin", label: "CCGS Sir John Franklin" },
  { value: "CCGS Sir Wilfred Grenfell", label: "CCGS Sir Wilfred Grenfell" },
  { value: "CCGS Sir Wilfrid Laurier", label: "CCGS Sir Wilfrid Laurier" },
  { value: "CCGS Spindrift", label: "CCGS Spindrift" },
  { value: "CCGS Spray", label: "CCGS Spray" },
  { value: "CCGS Stella Maris", label: "CCGS Stella Maris" },
  { value: "CCGS Taloyoak", label: "CCGS Taloyoak" },
  { value: "CCGS Tantallon", label: "CCGS Tantallon" },
  { value: "CCGS Tay", label: "CCGS Tay" },
  { value: "CCGS Teleost", label: "CCGS Teleost" },
  { value: "CCGS Terry Fox", label: "CCGS Terry Fox" },
  { value: "CCGS Theron", label: "CCGS Theron" },
  { value: "CCGS Thunder Cape", label: "CCGS Thunder Cape" },
  { value: "CCGS Tracy", label: "CCGS Tracy" },
  { value: "CCGS Tufts", label: "CCGS Tufts" },
  { value: "CCGS Vakta", label: "CCGS Vakta" },
  { value: "CCGS Vector", label: "CCGS Vector" },
  { value: "CCGS Verlen", label: "CCGS Verlen" },
  { value: "CCGS Vincent Massey", label: "CCGS Vincent Massey" },
  { value: "CCGS Viola M. Davidson", label: "CCGS Viola M. Davidson" },
  { value: "CCGS W.E. Ricker", label: "CCGS W.E. Ricker" },
  { value: "CCGS Westport", label: "CCGS Westport" },
  { value: "CCGS White", label: "CCGS White" },
  { value: "CCGS Wilfred Templeman", label: "CCGS Wilfred Templeman" },
  // Add more vessels as needed for a more comprehensive list
];

// You can add a function here to fetch/update this list from a source in a real app
