
import type { RiskAssessment, ApprovalStep, VesselDepartment, VesselRegion } from './types';

const now = new Date();
const oneDayAgo = new Date(now.getTime() - 24 * 60 * 60 * 1000);
const twoDaysAgo = new Date(now.getTime() - 2 * 24 * 60 * 60 * 1000);
const threeDaysAgo = new Date(now.getTime() - 3 * 24 * 60 * 60 * 1000);
const fourDaysAgo = new Date(now.getTime() - 4 * 24 * 60 * 60 * 1000);

const initialApprovalSteps: ApprovalStep[] = [
  { level: 'Crewing Standards and Oversight' },
  { level: 'Senior Director' },
  { level: 'Director General' },
];

export const mockRiskAssessments: RiskAssessment[] = [
  {
    id: 'ra-001',
    referenceNumber: 'CCG-RA-2024-001',
    vesselName: 'CCGS Amundsen',
    vesselIMO: '9275052',
    department: 'Navigation',
    region: 'Arctic',
    voyageDetails: 'Arctic Survey Mission, Resolute Bay to Kugluktuk, Departs 2024-07-15',
    reasonForRequest: 'Sailing with one less certified navigation officer.',
    personnelShortages: 'Missing 1x Navigational Watch Rating (NWR). Current NWR has exceeded work hours.',
    proposedOperationalDeviations: 'Master to take additional watch duty. Increased rest periods for remaining NWR.',
    submittedBy: 'Arctic Coordination Center', // Updated
    submissionDate: twoDaysAgo.toISOString(),
    submissionTimestamp: twoDaysAgo.getTime(),
    status: 'Pending Crewing Standards and Oversight',
    attachments: [
      { id: 'att-001', name: 'Crew_Manifest_Amundsen.pdf', url: '#', type: 'application/pdf', size: 102400, uploadedAt: twoDaysAgo.toISOString() },
      { id: 'att-002', name: 'Deviation_Request_Form_001.docx', url: '#', type: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document', size: 51200, uploadedAt: twoDaysAgo.toISOString() },
    ],
    approvalSteps: [
      { level: 'Crewing Standards and Oversight' },
      { level: 'Senior Director' },
      { level: 'Director General' },
    ],
    lastModified: twoDaysAgo.toISOString(),
    lastModifiedTimestamp: twoDaysAgo.getTime(),
    coDeptHeadSupportExemption: 'Yes',
    deptHeadConfidentInIndividual: 'Yes',
    deptHeadConfidenceReason: 'Individual has shown competence in simulated exercises and under direct supervision previously.',
    employeeFamiliarizationProvided: 'Yes',
    workedInDepartmentLast12Months: 'Yes',
    workedInDepartmentDetails: 'Served as Acting NWR for 2 months during Q1 2024.',
    similarResponsibilityExperience: 'Yes',
    similarResponsibilityDetails: 'Has assisted in navigational duties on similar voyages.',
    individualHasRequiredSeaService: 'No',
    individualWorkingTowardsCertification: 'Yes',
    certificationProgressSummary: 'All coursework completed. Final Transport Canada exam scheduled for August 2024. Bridge Watch Rating certificate is current.',
    requestCausesVacancyElsewhere: 'No',
    crewCompositionSufficientForSafety: 'Yes',
    detailedCrewCompetencyAssessment: 'All other crew members are fully certified for their roles. The Master and Chief Officer have extensive experience in Arctic waters. The impact of one less NWR is mitigated by adjustments to watch schedules and prioritizing critical tasks.',
    crewContinuityAsPerProfile: 'Yes',
    specialVoyageConsiderations: 'Voyage is in remote Arctic waters, limited external support. Weather can change rapidly. 24-hour daylight during this period.',
    reductionInVesselProgramRequirements: 'No',
  },
  {
    id: 'ra-002',
    referenceNumber: 'CCG-RA-2024-002',
    vesselName: 'CCGS Terry Fox',
    vesselIMO: '8127719',
    department: 'Engine Room',
    region: 'Atlantic',
    voyageDetails: 'Icebreaking Escort, St. John\'s to Strait of Belle Isle, Departs 2024-07-10',
    reasonForRequest: 'Chief Engineer certificate expired, renewal pending.',
    personnelShortages: 'Chief Engineer\'s CoC (Certificate of Competency) expired 2 days ago. Renewal paperwork submitted, awaiting issuance.',
    proposedOperationalDeviations: 'Second Engineer (holding valid CoC for the role) to assume Chief Engineer duties under remote supervision from shore-based Senior Chief Engineer. Daily operational checks to be reported.',
    submittedBy: 'Atlantic Fleet Desk', // Updated
    submissionDate: oneDayAgo.toISOString(),
    submissionTimestamp: oneDayAgo.getTime(),
    status: 'Pending Senior Director',
    attachments: [
      { id: 'att-003', name: 'TerryFox_CE_CoC_Expired.pdf', url: '#', type: 'application/pdf', size: 76800, uploadedAt: oneDayAgo.toISOString() },
      { id: 'att-004', name: 'Renewal_Application_Confirmation.png', dataAiHint:"document scan", url: 'https://placehold.co/150x100.png', type: 'image/png', size: 120000, uploadedAt: oneDayAgo.toISOString() },
    ],
    approvalSteps: [
      { level: 'Crewing Standards and Oversight', decision: 'Approved', userName: 'CSO Duty Officer', date: oneDayAgo.toISOString(), notes: 'Proceed with caution, ensure 2nd Eng is comfortable.' }, // Updated userName
      { level: 'Senior Director' },
      { level: 'Director General' },
    ],
    aiRiskScore: 65,
    aiSuggestedMitigations: 'Ensure constant communication link with shore-based Senior Chief Engineer. Implement a buddy system for critical engine room tasks. Limit vessel operations to daylight hours if possible until CoC is renewed.',
    aiRegulatoryConsiderations: 'Refer to Marine Personnel Regulations SOR/2007-115, Part 2, Division 7 regarding manning and certification. Exemption may be required under specific circumstances.',
    lastModified: oneDayAgo.toISOString(),
    lastModifiedTimestamp: oneDayAgo.getTime(),
    coDeptHeadSupportExemption: 'Yes',
    deptHeadConfidentInIndividual: 'Yes',
    deptHeadConfidenceReason: 'Second Engineer is highly capable and has shadowed CE extensively.',
    employeeFamiliarizationProvided: 'Yes',
    workedInDepartmentLast12Months: 'Yes',
    workedInDepartmentDetails: 'Continuously employed as Second Engineer for past 3 years.',
    similarResponsibilityExperience: 'Yes',
    similarResponsibilityDetails: 'Has covered Chief Engineer duties for short periods (up to 1 week) on 2 previous occasions.',
    individualHasRequiredSeaService: 'Yes',
    individualWorkingTowardsCertification: 'Yes', 
    certificationProgressSummary: 'Renewal application submitted to Transport Canada. All supporting docs provided.',
    requestCausesVacancyElsewhere: 'No',
    crewCompositionSufficientForSafety: 'Yes',
    detailedCrewCompetencyAssessment: 'All other engine room staff are certified. Second Engineer holds appropriate certification for their substantive role and is familiar with all systems.',
    crewContinuityAsPerProfile: 'Yes',
    specialVoyageConsiderations: 'Icebreaking operations demand high engine reliability. Constant monitoring planned.',
    reductionInVesselProgramRequirements: 'No',
  },
  {
    id: 'ra-003',
    referenceNumber: 'CCG-RA-2024-003',
    vesselName: 'CCGS Ann Harvey',
    vesselIMO: '8320442',
    department: 'Navigation',
    region: 'Atlantic',
    voyageDetails: 'SAR Patrol, Halifax Sector, Continuous Operations',
    reasonForRequest: 'Proposed reduction in minimum watchkeeping personnel during non-critical phases.',
    personnelShortages: 'No current shortage, but proposing a deviation to standard watchkeeping levels to manage crew fatigue on extended patrols.',
    proposedOperationalDeviations: 'During daylight hours and in clear weather (Visibility > 5NM, Wind < Force 4), reduce bridge watch to one certified officer and one lookout, from standard two officers and one lookout. Engine room to remain UMS (Unmanned Machinery Spaces) capable.',
    submittedBy: 'Central Logistics Team', // Updated (Example for variety)
    submissionDate: threeDaysAgo.toISOString(),
    submissionTimestamp: threeDaysAgo.getTime(),
    status: 'Approved',
    attachments: [
       { id: 'att-005', name: 'FatigueManagementPlan_AnnHarvey.pdf', url: '#', type: 'application/pdf', size: 204800, uploadedAt: threeDaysAgo.toISOString() },
    ],
    approvalSteps: [
      { level: 'Crewing Standards and Oversight', decision: 'Approved', userName: 'CSO Lead Reviewer', date: twoDaysAgo.toISOString(), notes: 'Acceptable under proposed conditions.'}, // Updated
      { level: 'Senior Director', decision: 'Approved', userName: 'A. Senior Director', date: oneDayAgo.toISOString(), notes: 'Concur with CSO assessment. Emphasize strict adherence.'}, // Updated
      { level: 'Director General', decision: 'Approved', userName: 'B. Director General', date: oneDayAgo.toISOString(), notes: 'Approved with condition that criteria for reduced watch are strictly adhered to and logged. Bi-hourly weather checks mandatory.'}, // Updated
    ],
    aiRiskScore: 30,
    aiGeneratedSummary: "Request for reduced watchkeeping on CCGS Ann Harvey during favorable conditions to manage crew fatigue. Proposes one officer and one lookout on bridge.",
    aiSuggestedMitigations: 'Implement strict criteria for "non-critical phases". Ensure immediate recall capability for full watch team. Regular fatigue assessments for watchkeepers.',
    aiRegulatoryConsiderations: 'Compliance with STCW Code Chapter VIII and Marine Personnel Regulations regarding watchkeeping arrangements and prevention of fatigue.',
    lastModified: oneDayAgo.toISOString(),
    lastModifiedTimestamp: oneDayAgo.getTime(),
    coDeptHeadSupportExemption: 'Yes',
    deptHeadConfidentInIndividual: 'Yes',
    deptHeadConfidenceReason: 'This is a general operational change, not specific to one individual. The Master confirms all watchkeeping officers are competent for this adjusted procedure under the specified conditions.',
    employeeFamiliarizationProvided: 'Yes',
    workedInDepartmentLast12Months: 'Yes',
    workedInDepartmentDetails: '',
    similarResponsibilityExperience: 'Yes',
    similarResponsibilityDetails: '',
    individualHasRequiredSeaService: 'Yes',
    individualWorkingTowardsCertification: 'Yes',
    certificationProgressSummary: '',
    requestCausesVacancyElsewhere: 'No',
    crewCompositionSufficientForSafety: 'Yes',
    detailedCrewCompetencyAssessment: 'All watchkeeping officers are fully certified and familiar with the vessel and operational area. This change relies on their existing high competency levels.',
    crewContinuityAsPerProfile: 'Yes',
    specialVoyageConsiderations: 'Applicable only during SAR patrol in designated sector, under strict weather and visibility criteria. Does not apply during active SAR cases or transits in congested waters.',
    reductionInVesselProgramRequirements: 'No',
  },
  {
    id: 'ra-004',
    referenceNumber: 'CCG-RA-2024-004',
    vesselName: 'CCGS Gordon Reid',
    vesselIMO: '8320454',
    department: 'Deck',
    region: 'Western',
    voyageDetails: 'Fisheries Patrol, West Coast Vancouver Island, Departs 2024-07-12',
    reasonForRequest: 'Medical evacuation of one Able Seaman, replacement not immediately available.',
    personnelShortages: 'One Able Seaman (AS) medevaced. Vessel will be short one AS for approximately 48-72 hours.',
    proposedOperationalDeviations: 'Remaining deck crew to absorb duties. Non-essential maintenance postponed. Mooring operations to be conducted with extra caution and supervision.',
    submittedBy: 'Western Region Operations', // Updated
    submissionDate: now.toISOString(),
    submissionTimestamp: now.getTime(),
    status: 'Pending Crewing Standards and Oversight',
    attachments: [
      { id: 'att-006', name: 'Medevac_Report_GR001.pdf', url: '#', type: 'application/pdf', size: 95000, uploadedAt: now.toISOString() },
    ],
    approvalSteps: [
      { level: 'Crewing Standards and Oversight' },
      { level: 'Senior Director' },
      { level: 'Director General' },
    ],
    lastModified: now.toISOString(),
    lastModifiedTimestamp: now.getTime(),
    coDeptHeadSupportExemption: 'Yes',
    deptHeadConfidentInIndividual: 'Yes',
    deptHeadConfidenceReason: 'Remaining deck crew are experienced and capable of managing the temporary shortage. The Bosun is particularly strong.',
    employeeFamiliarizationProvided: 'Yes',
    workedInDepartmentLast12Months: 'Yes',
    workedInDepartmentDetails: 'All remaining deck crew have served more than 12 months in their roles on this vessel.',
    similarResponsibilityExperience: 'Yes',
    similarResponsibilityDetails: 'Team has operated with minimum manning for short periods before due to training/appointments.',
    individualHasRequiredSeaService: 'Yes',
    individualWorkingTowardsCertification: 'No',
    certificationProgressSummary: '',
    requestCausesVacancyElsewhere: 'No',
    crewCompositionSufficientForSafety: 'Yes',
    detailedCrewCompetencyAssessment: 'The remaining deck ratings are fully certified. One Ordinary Seaman is less experienced but will be paired with a senior AB. All critical tasks (mooring, boat work) will have OOW oversight.',
    crewContinuityAsPerProfile: 'No',
    crewContinuityDetails: 'Short one AB, will be gapped for estimated 48-72 hours. All efforts to find replacement are underway.',
    specialVoyageConsiderations: 'Fisheries patrols involve boat work. Risk assessment for small boat launch/recovery will be heightened.',
    reductionInVesselProgramRequirements: 'Yes',
    rocNotificationOfLimitations: 'Yes',
  },
  {
    id: 'ra-005',
    referenceNumber: 'CCG-RA-2024-005',
    vesselName: 'CCGS Sir John Franklin',
    vesselIMO: '9744441',
    department: 'Navigation',
    region: 'Central',
    voyageDetails: 'Aids to Navigation maintenance, Great Lakes, Commences 2024-08-01',
    reasonForRequest: 'Gyrocompass requires overhaul, will operate on secondary magnetic compass.',
    personnelShortages: 'N/A directly, but primary navigation system impacted.',
    proposedOperationalDeviations: 'Reliance on magnetic compass as primary heading source. Regular cross-checks with GPS and visual bearings. Restricted operations in low visibility or complex waters until gyro is repaired.',
    submittedBy: 'Central Logistics Team', // Updated
    submissionDate: fourDaysAgo.toISOString(),
    submissionTimestamp: fourDaysAgo.getTime(),
    status: 'Rejected',
    attachments: [
      { id: 'att-007', name: 'Gyro_Maintenance_Report.pdf', url: '#', type: 'application/pdf', size: 150000, uploadedAt: fourDaysAgo.toISOString() },
      { id: 'att-008', name: 'Proposed_Nav_Procedures.docx', url: '#', type: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document', size: 65000, uploadedAt: fourDaysAgo.toISOString() },
    ],
    approvalSteps: [
      { level: 'Crewing Standards and Oversight', decision: 'Approved', userName: 'CSO Technical Unit', date: threeDaysAgo.toISOString(), notes: 'Mitigations seem adequate for short term.'}, // Updated
      { level: 'Senior Director', decision: 'Rejected', userName: 'A. Senior Director (NAVSAFE)', date: twoDaysAgo.toISOString(), notes: 'Operating on magnetic compass alone in the Great Lakes poses too high a risk. Gyro must be repaired or vessel operations significantly curtailed to daylight, clear weather, and open waters only.'}, // Updated
      { level: 'Director General' },
    ],
    aiRiskScore: 75,
    aiGeneratedSummary: "CCGS Sir John Franklin proposes operating with magnetic compass as primary due to gyro overhaul. Mitigations include GPS/visual checks and restricted ops in poor conditions.",
    aiSuggestedMitigations: "Prioritize gyrocompass repair. If proceeding, enhance watchkeeping, ensure all nav aids are fully operational. Consider shore-based navigational support.",
    aiRegulatoryConsiderations: "Refer to SOLAS Chapter V, Regulation 19 regarding carriage requirements for navigational equipment. Ensure compliance with Canada Shipping Act, 2001.",
    lastModified: twoDaysAgo.toISOString(),
    lastModifiedTimestamp: twoDaysAgo.getTime(),
    coDeptHeadSupportExemption: 'Yes',
    deptHeadConfidentInIndividual: 'Yes',
    deptHeadConfidenceReason: 'All navigating officers are trained and certified in traditional navigation techniques, including primary reliance on magnetic compass.',
    employeeFamiliarizationProvided: 'Yes',
    workedInDepartmentLast12Months: 'Yes',
    workedInDepartmentDetails: 'All OOWs are experienced on this vessel class.',
    similarResponsibilityExperience: 'Yes',
    similarResponsibilityDetails: 'Magnetic compass navigation is a fundamental skill, routinely practiced.',
    individualHasRequiredSeaService: 'Yes',
    individualWorkingTowardsCertification: 'No',
    certificationProgressSummary: '',
    requestCausesVacancyElsewhere: 'No',
    crewCompositionSufficientForSafety: 'Yes',
    detailedCrewCompetencyAssessment: 'All navigating officers meet requirements. The primary risk is equipment-based, not personnel competency with the alternative method.',
    crewContinuityAsPerProfile: 'Yes',
    specialVoyageConsiderations: 'Great Lakes can have high traffic density and variable weather. Navigating by magnetic compass requires heightened diligence.',
    reductionInVesselProgramRequirements: 'Yes',
    rocNotificationOfLimitations: 'Yes',
  }
];

    